<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('schools')->delete();
        
        \DB::table('schools')->insert(array (
            0 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:05:52',
                'grading_id' => 17,
                'id' => 1,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Abra State Institute of Science and Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:05:52',
            ),
            1 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:08:22',
                'grading_id' => 16,
                'id' => 2,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Apayao State College',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:08:22',
            ),
            2 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-26 22:09:52',
                'grading_id' => 16,
                'id' => 3,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Saint Louis University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:09:52',
            ),
            3 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-26 22:11:45',
                'grading_id' => 16,
                'id' => 4,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of the Cordilleras',
                'term_id' => 13,
                'updated_at' => '2022-08-26 22:11:45',
            ),
            4 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:19:20',
                'grading_id' => 17,
                'id' => 5,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of the Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:19:20',
            ),
            5 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:21:27',
                'grading_id' => 17,
                'id' => 6,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Benguet State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:21:27',
            ),
            6 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:23:55',
                'grading_id' => 16,
                'id' => 7,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ifugao State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:23:55',
            ),
            7 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:30:42',
                'grading_id' => 17,
                'id' => 8,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Kalinga State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:30:42',
            ),
            8 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:32:25',
                'grading_id' => 16,
                'id' => 9,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Mountain Province State Polytechnic College',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:32:25',
            ),
            9 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-26 22:34:54',
                'grading_id' => 16,
                'id' => 10,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Baguio',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:34:54',
            ),
            10 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 22:38:26',
                'grading_id' => 17,
                'id' => 11,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Mariano Marcos State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 22:38:26',
            ),
            11 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 23:41:15',
                'grading_id' => 16,
                'id' => 12,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'North Luzon Philippines State College',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:41:15',
            ),
            12 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 23:43:38',
                'grading_id' => 17,
                'id' => 13,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ilocos Sur Polytechnic State College',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:43:38',
            ),
            13 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 23:45:23',
                'grading_id' => 17,
                'id' => 14,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Northern Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:45:23',
            ),
            14 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 23:48:44',
                'grading_id' => 16,
                'id' => 15,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Don Mariano Marcos Memorial State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:48:44',
            ),
            15 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-26 23:51:44',
                'grading_id' => 16,
                'id' => 16,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Lorma Colleges',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:51:44',
            ),
            16 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-26 23:52:57',
                'grading_id' => 16,
                'id' => 17,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Saint Louis College',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:52:57',
            ),
            17 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-26 23:55:59',
                'grading_id' => 17,
                'id' => 18,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Pangasinan State University',
                'term_id' => 12,
                'updated_at' => '2022-08-26 23:55:59',
            ),
            18 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:00:01',
                'grading_id' => 16,
                'id' => 19,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Lyceum-Northwestern University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:00:01',
            ),
            19 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:01:21',
                'grading_id' => 16,
                'id' => 20,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University de Dagupan',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:01:21',
            ),
            20 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:02:28',
                'grading_id' => 16,
                'id' => 21,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Luzon',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:02:28',
            ),
            21 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:05:35',
                'grading_id' => 17,
                'id' => 22,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Pangasinan',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:05:35',
            ),
            22 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:09:05',
                'grading_id' => 16,
                'id' => 23,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Virgen Milagrosa University Foundation',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:09:05',
            ),
            23 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 00:12:48',
                'grading_id' => 16,
                'id' => 24,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Urdaneta City University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:12:48',
            ),
            24 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 00:48:59',
                'grading_id' => 17,
                'id' => 25,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Batanes State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:48:59',
            ),
            25 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 00:50:13',
                'grading_id' => 17,
                'id' => 26,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cagayan State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:50:13',
            ),
            26 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 00:57:50',
                'grading_id' => 16,
                'id' => 27,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Saint Louis',
                'term_id' => 12,
                'updated_at' => '2022-08-27 00:57:50',
            ),
            27 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:02:04',
                'grading_id' => 17,
                'id' => 28,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Isabela State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:02:04',
            ),
            28 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:05:27',
                'grading_id' => 17,
                'id' => 29,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ama College',
                'term_id' => 13,
                'updated_at' => '2022-08-27 01:05:27',
            ),
            29 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:09:27',
                'grading_id' => 17,
                'id' => 30,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Philippine Normal University',
                'term_id' => 13,
                'updated_at' => '2022-08-27 01:09:27',
            ),
            30 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:12:01',
                'grading_id' => 17,
                'id' => 31,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Nueva Vizcaya State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:12:01',
            ),
            31 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:13:29',
                'grading_id' => 16,
                'id' => 32,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Saint Mary\'s University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:13:29',
            ),
            32 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:20:38',
                'grading_id' => 17,
                'id' => 33,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Quirino State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:20:38',
            ),
            33 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:24:59',
                'grading_id' => 17,
                'id' => 34,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Aurora State College of Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:24:59',
            ),
            34 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:26:15',
                'grading_id' => 17,
                'id' => 35,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bataan Heroes Memorial College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:26:15',
            ),
            35 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:30:04',
                'grading_id' => 17,
                'id' => 36,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bataan Peninsula State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:30:04',
            ),
            36 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:32:54',
                'grading_id' => 17,
                'id' => 37,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bulacan State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:32:54',
            ),
            37 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:40:55',
                'grading_id' => 17,
                'id' => 38,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Centro Escolar University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:40:55',
            ),
            38 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:43:40',
                'grading_id' => 17,
                'id' => 39,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Polytechnic College of the City of Meycauyan',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:43:40',
            ),
            39 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:45:41',
                'grading_id' => 17,
                'id' => 40,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bulacan Agricultural State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:45:41',
            ),
            40 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:49:27',
                'grading_id' => 17,
                'id' => 41,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Polytechnic University of the Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:49:27',
            ),
            41 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:53:54',
                'grading_id' => 17,
                'id' => 42,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Nueva Ecija University of Science & Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:53:54',
            ),
            42 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 01:55:02',
                'grading_id' => 17,
                'id' => 43,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Central Luzon State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:55:02',
            ),
            43 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:56:10',
                'grading_id' => 16,
                'id' => 44,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Angeles University Foundation',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:56:10',
            ),
            44 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:56:59',
                'grading_id' => 17,
                'id' => 45,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Holy Angel University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:56:59',
            ),
            45 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 01:58:37',
                'grading_id' => 17,
                'id' => 46,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Systems Plus College Foundation',
                'term_id' => 12,
                'updated_at' => '2022-08-27 01:58:37',
            ),
            46 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:00:29',
                'grading_id' => 17,
                'id' => 47,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Don Honorio Vetura State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:00:29',
            ),
            47 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:01:49',
                'grading_id' => 17,
                'id' => 48,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Pampanga State Agricultural University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:01:49',
            ),
            48 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:07:38',
                'grading_id' => 17,
                'id' => 49,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Our Lady of Fatima University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:07:38',
            ),
            49 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:10:14',
                'grading_id' => 17,
                'id' => 50,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Tarlac Agricultural University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:10:14',
            ),
            50 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:11:07',
                'grading_id' => 17,
                'id' => 51,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Tarlac State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:11:07',
            ),
            51 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:15:08',
                'grading_id' => 17,
                'id' => 52,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'President Ramon Magsaysay State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:15:08',
            ),
            52 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:18:40',
                'grading_id' => 17,
                'id' => 53,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Lyceum of the Philippines University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:18:40',
            ),
            53 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:19:46',
                'grading_id' => 17,
                'id' => 54,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Batangas',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:19:46',
            ),
            54 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:21:38',
                'grading_id' => 17,
                'id' => 55,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Batangas State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:21:38',
            ),
            55 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:23:17',
                'grading_id' => 17,
                'id' => 56,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'De La Salle University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:23:17',
            ),
            56 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:28:44',
                'grading_id' => 17,
                'id' => 57,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Lipa City Colleges',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:28:44',
            ),
            57 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:32:41',
                'grading_id' => 16,
                'id' => 58,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'First Asia Institute of Technology Humanity',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:32:41',
            ),
            58 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:39:08',
                'grading_id' => 16,
                'id' => 59,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'St. Dominic College of Asia',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:39:08',
            ),
            59 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:43:08',
                'grading_id' => 17,
                'id' => 60,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cavite State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:43:08',
            ),
            60 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:53:33',
                'grading_id' => 17,
                'id' => 61,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Emilio Aguinaldo College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:53:33',
            ),
            61 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 02:56:12',
                'grading_id' => 17,
                'id' => 62,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Technological University of the Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:56:12',
            ),
            62 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 02:59:42',
                'grading_id' => 17,
                'id' => 63,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Adventist University of the Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 02:59:42',
            ),
            63 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:01:10',
                'grading_id' => 17,
                'id' => 64,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Saint Michael\'s College of Laguna',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:01:10',
            ),
            64 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:03:02',
                'grading_id' => 17,
                'id' => 65,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Perpetual Help',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:03:02',
            ),
            65 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:08:58',
                'grading_id' => 17,
                'id' => 66,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Colegio de San Juan de Letran',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:08:58',
            ),
            66 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:13:31',
                'grading_id' => 17,
                'id' => 67,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Laguna State Polytechnic University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:13:31',
            ),
            67 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:17:20',
                'grading_id' => 16,
                'id' => 68,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'San Pablo College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:17:20',
            ),
            68 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:20:00',
                'grading_id' => 17,
                'id' => 69,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Southern Luzon State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:20:00',
            ),
            69 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:24:05',
                'grading_id' => 17,
                'id' => 70,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Manuel S. Enverga University Foundation Inc.',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:24:05',
            ),
            70 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:25:22',
                'grading_id' => 17,
                'id' => 71,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Rizal System',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:25:22',
            ),
            71 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:30:24',
                'grading_id' => 17,
                'id' => 72,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Marinduque State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:30:24',
            ),
            72 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:31:31',
                'grading_id' => 16,
                'id' => 73,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Occidental Mindoro State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:31:31',
            ),
            73 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:32:50',
                'grading_id' => 17,
                'id' => 74,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Mindoro State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:32:50',
            ),
            74 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:35:22',
                'grading_id' => 17,
                'id' => 75,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bicol University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:35:22',
            ),
            75 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:37:19',
                'grading_id' => 17,
                'id' => 76,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Camarines Norte State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:37:19',
            ),
            76 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:38:29',
                'grading_id' => 17,
                'id' => 77,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Partido State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:38:29',
            ),
            77 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:40:31',
                'grading_id' => 17,
                'id' => 78,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Camarines Sur Polytechnic Colleges',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:40:31',
            ),
            78 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:41:46',
                'grading_id' => 16,
                'id' => 79,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ateneo De Naga University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:41:46',
            ),
            79 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:44:49',
                'grading_id' => 17,
                'id' => 80,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bicol State College of Applied Sciences and Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:44:49',
            ),
            80 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:46:09',
                'grading_id' => 17,
                'id' => 81,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Central Bicol State University of Agriculture',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:46:09',
            ),
            81 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:47:38',
                'grading_id' => 17,
                'id' => 82,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Catanduanes State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:47:38',
            ),
            82 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:48:31',
                'grading_id' => 17,
                'id' => 83,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Sorsogon State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:48:31',
            ),
            83 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:51:10',
                'grading_id' => 17,
                'id' => 84,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Guimaras State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:51:10',
            ),
            84 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 03:51:53',
                'grading_id' => 17,
                'id' => 85,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Central Philippine University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:51:53',
            ),
            85 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:53:17',
                'grading_id' => 17,
                'id' => 86,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Iloilo Science and Technology University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:53:17',
            ),
            86 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 03:57:47',
                'grading_id' => 17,
                'id' => 87,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of the Philippines Visayas',
                'term_id' => 12,
                'updated_at' => '2022-08-27 03:57:47',
            ),
            87 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 04:01:01',
                'grading_id' => 17,
                'id' => 88,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'West Visayas State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 04:01:01',
            ),
            88 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 06:04:22',
                'grading_id' => 17,
                'id' => 89,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bohol Island State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:04:22',
            ),
            89 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:05:37',
                'grading_id' => 17,
                'id' => 90,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Holy Name University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:05:37',
            ),
            90 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:06:53',
                'grading_id' => 17,
                'id' => 91,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cebu Institute of Technology-University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:06:53',
            ),
            91 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 06:07:30',
                'grading_id' => 17,
                'id' => 92,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cebu Normal University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:07:30',
            ),
            92 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 06:47:16',
                'grading_id' => 17,
                'id' => 93,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cebu Technological University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:47:16',
            ),
            93 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:48:33',
                'grading_id' => 16,
                'id' => 94,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Southwestern University Philippine Investment and Management',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:48:33',
            ),
            94 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:50:53',
                'grading_id' => 16,
                'id' => 95,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Cebu',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:50:53',
            ),
            95 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:52:00',
                'grading_id' => 17,
                'id' => 96,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of San Carlos',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:52:00',
            ),
            96 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:52:56',
                'grading_id' => 17,
                'id' => 97,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of San Jose - Recoletos',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:52:56',
            ),
            97 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:54:59',
                'grading_id' => 17,
                'id' => 98,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Southern Philippines Foundation',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:54:59',
            ),
            98 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:57:49',
                'grading_id' => 17,
                'id' => 99,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of the Visayas',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:57:49',
            ),
            99 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 06:58:41',
                'grading_id' => 17,
                'id' => 100,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Foundation University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 06:58:41',
            ),
            100 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:00:01',
                'grading_id' => 17,
                'id' => 101,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Negros Oriental State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:00:01',
            ),
            101 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 07:00:46',
                'grading_id' => 17,
                'id' => 102,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Silliman University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:00:46',
            ),
            102 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 07:06:57',
                'grading_id' => 17,
                'id' => 103,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'St. Paul University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:06:57',
            ),
            103 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:10:12',
                'grading_id' => 17,
                'id' => 104,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Biliran Province State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:10:12',
            ),
            104 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:11:35',
                'grading_id' => 17,
                'id' => 105,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Eastern Samar State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:11:35',
            ),
            105 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:15:56',
                'grading_id' => 17,
                'id' => 106,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Visayas State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:15:56',
            ),
            106 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:18:13',
                'grading_id' => 17,
                'id' => 107,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Eastern Visayas State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:18:13',
            ),
            107 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 07:19:15',
                'grading_id' => 17,
                'id' => 108,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'San Lorenzo Ruiz College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:19:15',
            ),
            108 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:21:11',
                'grading_id' => 17,
                'id' => 109,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Palompon Institute of Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:21:11',
            ),
            109 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 07:22:23',
                'grading_id' => 17,
                'id' => 110,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Asian Development Foundation College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:22:23',
            ),
            110 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:24:11',
                'grading_id' => 17,
                'id' => 111,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Leyte Normal University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:24:11',
            ),
            111 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:30:53',
                'grading_id' => 17,
                'id' => 112,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Eastern Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:30:53',
            ),
            112 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:32:17',
                'grading_id' => 17,
                'id' => 113,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Southern Leyte State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:32:17',
            ),
            113 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 07:33:57',
                'grading_id' => 17,
                'id' => 114,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Saint Joseph College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:33:57',
            ),
            114 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:49:57',
                'grading_id' => 17,
                'id' => 115,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Northwest Samar State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:49:57',
            ),
            115 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:50:58',
                'grading_id' => 17,
                'id' => 116,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Samar College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:50:58',
            ),
            116 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 07:53:15',
                'grading_id' => 17,
                'id' => 117,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Samar State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 07:53:15',
            ),
            117 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 08:10:37',
                'grading_id' => 17,
                'id' => 118,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Jose Rizal Memorial State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:10:37',
            ),
            118 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 08:13:59',
                'grading_id' => 17,
                'id' => 119,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Mindanao State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:13:59',
            ),
            119 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 08:15:13',
                'grading_id' => 17,
                'id' => 120,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ateneo de Zamboanga University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:15:13',
            ),
            120 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 08:19:26',
                'grading_id' => 17,
                'id' => 121,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'JH Cerilles State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:19:26',
            ),
            121 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 08:20:22',
                'grading_id' => 17,
                'id' => 122,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Western Mindanao State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:20:22',
            ),
            122 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 08:22:11',
                'grading_id' => 17,
                'id' => 123,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Zamboanga Peninsula Polytechnic State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 08:22:11',
            ),
            123 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:08:47',
                'grading_id' => 17,
                'id' => 124,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Bukidnon State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:08:47',
            ),
            124 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:09:35',
                'grading_id' => 17,
                'id' => 125,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'San Isidro College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:09:35',
            ),
            125 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:10:44',
                'grading_id' => 17,
                'id' => 126,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Central Mindanao University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:10:44',
            ),
            126 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:12:27',
                'grading_id' => 17,
                'id' => 127,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Camiguin Polytechnic State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:12:27',
            ),
            127 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:16:37',
                'grading_id' => 17,
                'id' => 128,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Science & Technology of Southern Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:16:37',
            ),
            128 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:18:14',
                'grading_id' => 17,
                'id' => 129,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Misamis University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:18:14',
            ),
            129 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:19:33',
                'grading_id' => 17,
                'id' => 130,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Northwestern Mindanao State College of Science & Technology',
                'term_id' => 13,
                'updated_at' => '2022-08-27 22:19:33',
            ),
            130 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:20:26',
                'grading_id' => 17,
                'id' => 131,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Capitol University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:20:26',
            ),
            131 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:27:26',
                'grading_id' => 17,
                'id' => 132,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Liceo de Cagayan University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:27:26',
            ),
            132 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:28:02',
                'grading_id' => 17,
                'id' => 133,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Lourdes College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:28:02',
            ),
            133 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 22:31:21',
                'grading_id' => 17,
                'id' => 134,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Xavier University - Ateneo de Cagayan',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:31:21',
            ),
            134 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:37:34',
                'grading_id' => 17,
                'id' => 135,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Davao de Oro State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:37:34',
            ),
            135 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:38:37',
                'grading_id' => 17,
                'id' => 136,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Monkayo College of Arts, Sciences and Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:38:37',
            ),
            136 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:40:06',
                'grading_id' => 17,
                'id' => 137,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Kapalong College of Agriculture, Sciences and Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:40:06',
            ),
            137 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 22:41:00',
                'grading_id' => 17,
                'id' => 138,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Davao del Norte State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 22:41:00',
            ),
            138 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:28:54',
                'grading_id' => 17,
                'id' => 139,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Mindanao',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:28:54',
            ),
            139 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:29:54',
                'grading_id' => 17,
                'id' => 140,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Southeastern Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:29:54',
            ),
            140 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:31:46',
                'grading_id' => 17,
                'id' => 141,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ateneo de Davao University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:31:46',
            ),
            141 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:32:43',
                'grading_id' => 16,
                'id' => 142,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Brokenshire College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:32:43',
            ),
            142 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:33:24',
                'grading_id' => 17,
                'id' => 143,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Davao Doctors College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:33:24',
            ),
            143 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:34:13',
                'grading_id' => 16,
                'id' => 144,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'San Pedro College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:34:13',
            ),
            144 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:35:01',
                'grading_id' => 16,
                'id' => 145,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Immaculate Conception',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:35:01',
            ),
            145 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:41:05',
                'grading_id' => 17,
                'id' => 146,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cor Jesu College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:41:05',
            ),
            146 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:41:52',
                'grading_id' => 17,
                'id' => 147,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Davao del Sur State College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:41:52',
            ),
            147 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:44:34',
                'grading_id' => 17,
                'id' => 148,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Davao Oriental State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:44:34',
            ),
            148 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:46:51',
                'grading_id' => 17,
                'id' => 149,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Southern Mindanao',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:46:51',
            ),
            149 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:49:20',
                'grading_id' => 16,
                'id' => 150,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ramon Magsaysay Memorial Colleges',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:49:20',
            ),
            150 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:50:20',
                'grading_id' => 17,
                'id' => 151,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Notre Dame of Marbel University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:50:20',
            ),
            151 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:51:34',
                'grading_id' => 17,
                'id' => 152,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Sultan Kudarat State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:51:34',
            ),
            152 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:53:04',
                'grading_id' => 17,
                'id' => 153,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Butuan Doctors College',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:53:04',
            ),
            153 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:53:56',
                'grading_id' => 17,
                'id' => 154,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Caraga State University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:53:56',
            ),
            154 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-27 23:55:01',
                'grading_id' => 17,
                'id' => 155,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Father Saturnino Urios University',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:55:01',
            ),
            155 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-27 23:57:04',
                'grading_id' => 17,
                'id' => 156,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Agusan del Sur State College of Agriculture & Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-27 23:57:04',
            ),
            156 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:01:52',
                'grading_id' => 17,
                'id' => 157,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Surigao Del Norte State University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:01:52',
            ),
            157 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:10:16',
                'grading_id' => 17,
                'id' => 158,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'STI College',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:10:16',
            ),
            158 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:12:20',
                'grading_id' => 16,
                'id' => 159,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Surigao Doctors College',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:12:20',
            ),
            159 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:13:26',
                'grading_id' => 17,
                'id' => 160,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'North Eastern Mindanao State University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:13:26',
            ),
            160 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:30:53',
                'grading_id' => 17,
                'id' => 161,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Cotabato State University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:30:53',
            ),
            161 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:34:16',
                'grading_id' => 17,
                'id' => 162,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Sulu State College',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:34:16',
            ),
            162 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:35:08',
                'grading_id' => 17,
                'id' => 163,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Tawi-tawi Regional Agricultural College',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:35:08',
            ),
            163 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:42:04',
                'grading_id' => 17,
                'id' => 164,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Manila Central University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:42:04',
            ),
            164 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:43:04',
                'grading_id' => 17,
                'id' => 165,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of the East',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:43:04',
            ),
            165 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:44:11',
                'grading_id' => 17,
                'id' => 166,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Southville International School',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:44:11',
            ),
            166 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:51:12',
                'grading_id' => 17,
                'id' => 167,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Asia Pacific College',
                'term_id' => 13,
                'updated_at' => '2022-08-28 00:51:12',
            ),
            167 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:53:04',
                'grading_id' => 17,
                'id' => 168,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Mapua University',
                'term_id' => 14,
                'updated_at' => '2022-08-28 00:53:04',
            ),
            168 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:53:50',
                'grading_id' => 17,
                'id' => 169,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Jose Rizal University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:53:50',
            ),
            169 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 00:54:57',
                'grading_id' => 17,
                'id' => 170,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Rizal Technological University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:54:57',
            ),
            170 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 00:55:40',
                'grading_id' => 17,
                'id' => 171,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Adamson University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 00:55:40',
            ),
            171 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 01:03:39',
                'grading_id' => 17,
                'id' => 172,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Eulogio \'Amang\' Rodriguez Institute of Science & Technology',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:03:39',
            ),
            172 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:04:58',
                'grading_id' => 17,
                'id' => 173,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Far Eastern University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:04:58',
            ),
            173 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:06:36',
                'grading_id' => 17,
                'id' => 174,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Far Eastern University Institute of Technology',
                'term_id' => 13,
                'updated_at' => '2022-08-28 01:06:36',
            ),
            174 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:09:42',
                'grading_id' => 17,
                'id' => 175,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'National University',
                'term_id' => 13,
                'updated_at' => '2022-08-28 01:09:42',
            ),
            175 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 01:10:37',
                'grading_id' => 17,
                'id' => 176,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Pamantasan ng Lungsod ng Maynila',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:10:37',
            ),
            176 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:13:11',
                'grading_id' => 17,
                'id' => 177,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Philippine Women\'s University',
                'term_id' => 13,
                'updated_at' => '2022-08-28 01:13:11',
            ),
            177 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:15:42',
                'grading_id' => 17,
                'id' => 178,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'San Sebastian College - Recoletos',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:15:42',
            ),
            178 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:16:58',
                'grading_id' => 17,
                'id' => 179,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Technological Institute of the Philippines',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:16:58',
            ),
            179 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:17:39',
                'grading_id' => 17,
                'id' => 180,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Universidad de Manila',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:17:39',
            ),
            180 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:18:37',
                'grading_id' => 17,
                'id' => 181,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Santo Tomas',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:18:37',
            ),
            181 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 01:22:56',
                'grading_id' => 17,
                'id' => 182,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Pamantasan ng Lungsod ng Muntinlupa',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:22:56',
            ),
            182 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:24:03',
                'grading_id' => 17,
                'id' => 183,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'PATTS College of Aeronautics',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:24:03',
            ),
            183 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 01:26:43',
                'grading_id' => 17,
                'id' => 184,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Philippine State College of Aeronautics',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:26:43',
            ),
            184 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:27:51',
                'grading_id' => 17,
                'id' => 185,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'University of Asia and the Pacific',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:27:51',
            ),
            185 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:29:01',
                'grading_id' => 17,
                'id' => 186,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'AMA Computer University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:29:01',
            ),
            186 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:29:48',
                'grading_id' => 17,
                'id' => 187,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Ateneo de Manila University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:29:48',
            ),
            187 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:31:39',
                'grading_id' => 17,
                'id' => 188,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'New Era University',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:31:39',
            ),
            188 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 7,
                'code' => NULL,
                'created_at' => '2022-08-28 01:35:45',
                'grading_id' => 17,
                'id' => 189,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Trinity University of Asia',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:35:45',
            ),
            189 => 
            array (
                'avatar' => 'school.jpg',
                'class_id' => 8,
                'code' => NULL,
                'created_at' => '2022-08-28 01:40:22',
                'grading_id' => 17,
                'id' => 190,
                'is_active' => 1,
                'is_upsystem' => 0,
                'name' => 'Pamantasan ng Lungsod ng Valenzuela',
                'term_id' => 12,
                'updated_at' => '2022-08-28 01:40:22',
            ),
        ));
        
        
    }
}