export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: [],
    },
    {
        id: 3,
        label: "Users",
        icon: "bxs-face",
        link: "/users",
        component: "Users/Index",
        name: "Users",
        user: ['Super Administrator'],
    },
    {
        id: 33,
        label: "Scholars",
        icon: "bx-user-circle",
        link: "/scholars",
        component: "Scholars/Index",
        name: "Scholars",
        user: ['Super Administrator'],
    },
    {
        id: 4,
        label: "Addresses",
        icon: "bx-map",
        link: "/addresses",
        component: "Addresses/Index",
        name: "Addresses",
        user: ['Super Administrator'],
    },
    {
        id: 5,
        label: "Agencies",
        icon: "bxs-city",
        link: "/agencies",
        component: "Agencies/Index",
        name: "Agencies",
        user: ['Super Administrator'],
    },
    {
        id: 6,
        label: "Programs",
        icon: "bx-category-alt",
        link: "/programs",
        component: "Programs/Index",
        name: "Programs",
        user: ['Super Administrator'],
    },
    {
        id: 66,
        label: "Privileges",
        icon: "bx-wallet",
        link: "/privileges",
        component: "Privileges/Index",
        name: "Privileges",
        user: ['Super Administrator'],
    },
    {
        id: 7,
        label: "Expenses",
        icon: "bx-credit-card-alt",
        link: "/expenses",
        component: "Expenses/Index",
        name: "Expenses",
        user: ['Super Administrator'],
    },
    {
        id: 8,
        label: "Schools",
        icon: "bxs-school",
        link: "/schools",
        component: "Schools/Index",
        name: "Schools",
        user: ['Super Administrator'],
    },
    {
        id: 9,
        label: "Courses",
        icon: "bxs-graduation",
        link: "/courses",
        component: "Courses/Index",
        name: "Courses",
        user: ['Super Administrator'],
    },
];